"""add_all_order_status_values

Revision ID: 019286e6c789
Revises: 1dedd9d1802f
Create Date: 2026-03-12 14:26:30.808842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019286e6c789'
down_revision = '1dedd9d1802f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем все недостающие значения в enum orderstatus
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'cooking'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
