"""add subscription fields to orders

Revision ID: 053400ff6a1e
Revises: 3a1_subs_no_discount
Create Date: 2026-03-09 23:58:20.336405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '053400ff6a1e'
down_revision = '3a1_subs_no_discount'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_images_id'), 'food_images', ['id'], unique=False)
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('branch_revenue')
    op.drop_column('foods', 'image_url')
    op.add_column('orders', sa.Column('paid_by_subscription', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'subscriptions', ['subscription_id'], ['id'])
    op.drop_constraint('subscriptions_branch_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'branch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subscriptions_branch_id_fkey', 'subscriptions', 'branches', ['branch_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'subscription_id')
    op.drop_column('orders', 'paid_by_subscription')
    op.add_column('foods', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('branch_revenue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('final_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='branch_revenue_branch_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='branch_revenue_order_id_fkey'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name='branch_revenue_subscription_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='branch_revenue_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='branch_revenue_pkey')
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('ORDER', 'PAYMENT', 'SYSTEM', 'DELIVERY', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('UNREAD', 'READ', 'ARCHIVED', name='notificationstatus'), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='notifications_branch_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='notifications_order_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.drop_index(op.f('ix_food_images_id'), table_name='food_images')
    op.drop_table('food_images')
    # ### end Alembic commands ###
