"""add_is_paid_to_orders

Revision ID: 106c4b41f7a0
Revises: fcb96b92c67d
Create Date: 2026-03-18 06:02:07.284543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106c4b41f7a0'
down_revision = 'fcb96b92c67d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_paid')
    # ### end Alembic commands ###
