"""add food_name to order_items

Revision ID: 1cddc4b7c37a
Revises: 053400ff6a1e
Create Date: 2026-03-10 00:00:07.810297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cddc4b7c37a'
down_revision = '053400ff6a1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('food_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'food_name')
    # ### end Alembic commands ###
