"""add_cooking_status_to_enum

Revision ID: 1dedd9d1802f
Revises: 1cddc4b7c37a
Create Date: 2026-03-12 14:25:23.923036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dedd9d1802f'
down_revision = '1cddc4b7c37a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем значение 'cooking' в enum orderstatus
    op.execute("ALTER TYPE orderstatus ADD VALUE 'cooking'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем значение 'cooking' из enum orderstatus
    op.execute("ALTER TYPE orderstatus RENAME TO orderstatus_old")
    op.execute("CREATE TYPE orderstatus AS ENUM ('pending', 'accepted', 'ready', 'given', 'cancelled')")
    op.execute("ALTER TABLE orders ALTER COLUMN status TYPE orderstatus USING status::text::orderstatus")
    op.execute("DROP TYPE orderstatus_old")
    # ### end Alembic commands ###
