"""change_goal_to_string

Revision ID: 371157f98271
Revises: 106c4b41f7a0
Create Date: 2026-03-23 20:34:40.831957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '371157f98271'
down_revision = '106c4b41f7a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_profiles', 'goal',
               existing_type=postgresql.ENUM('lose_weight', 'gain_weight', 'maintain', name='goal'),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('users', 'bio')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('ai_profiles', 'goal',
               existing_type=sa.String(),
               type_=postgresql.ENUM('lose_weight', 'gain_weight', 'maintain', name='goal'),
               existing_nullable=True)
    # ### end Alembic commands ###
