"""fix

Revision ID: 8119ef07c6c0
Revises: 4221052ac524
Create Date: 2026-02-17 11:04:48.243993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8119ef07c6c0'
down_revision = '4221052ac524'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch_revenue', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('branch_revenue', sa.Column('discount_amount', sa.Float(), nullable=False))
    op.add_column('branch_revenue', sa.Column('final_amount', sa.Float(), nullable=False))
    op.alter_column('branch_revenue', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('branch_revenue', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_users_phone', 'users', ['phone'], unique=True)
    op.alter_column('branch_revenue', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('branch_revenue', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('branch_revenue', 'final_amount')
    op.drop_column('branch_revenue', 'discount_amount')
    op.drop_column('branch_revenue', 'amount')
    # ### end Alembic commands ###
