"""fix

Revision ID: 86f66a672e93
Revises: 18bbd62e079e
Create Date: 2026-02-12 13:37:19.267276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f66a672e93'
down_revision = '18bbd62e079e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch_revenue', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.add_column('branch_revenue', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'branch_revenue', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'branch_revenue', 'subscriptions', ['subscription_id'], ['id'])
    op.drop_column('branch_revenue', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch_revenue', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'branch_revenue', type_='foreignkey')
    op.drop_constraint(None, 'branch_revenue', type_='foreignkey')
    op.drop_column('branch_revenue', 'user_id')
    op.drop_column('branch_revenue', 'subscription_id')
    # ### end Alembic commands ###
