"""add image_url to food

Revision ID: c13310791474
Revises: d1a47cdeb017
Create Date: 2026-03-17 09:59:36.916168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13310791474'
down_revision = 'd1a47cdeb017'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'image_url')
    # ### end Alembic commands ###
