"""Add MenuType and branch_menus table

Revision ID: c64f7a75b844
Revises: 4b2_subscription_menus
Create Date: 2026-03-17 00:41:51.697210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64f7a75b844'
down_revision = '4b2_subscription_menus'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create the Enum type in Postgres first
    menutype_enum = sa.Enum('SUBSCRIPTION', 'REGULAR', name='menutype')
    menutype_enum.create(op.get_bind(), checkfirst=True)

    # Create the branch_menus table
    op.create_table('branch_menus',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('branch_id', sa.Integer(), nullable=False),
        sa.Column('food_id', sa.Integer(), nullable=False),
        sa.Column('is_available', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
        sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('branch_id', 'food_id', name='uq_branch_food')
    )
    op.create_index(op.f('ix_branch_menus_id'), 'branch_menus', ['id'], unique=False)
    
    # Add columns to foods
    op.add_column('foods', sa.Column('menu_type', menutype_enum, nullable=False, server_default='REGULAR'))
    op.add_column('foods', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('foods', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    
    # Drop old constraints and columns
    op.drop_constraint('foods_branch_id_fkey', 'foods', type_='foreignkey')
    op.drop_column('foods', 'is_available')
    op.drop_column('foods', 'branch_id')
    
    # Add new foreign keys
    op.create_foreign_key('fk_food_owner_id', 'foods', 'users', ['owner_id'], ['id'])
    op.create_foreign_key('fk_food_restaurant_id', 'foods', 'restaurants', ['restaurant_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('foods', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'foods', type_='foreignkey')
    op.drop_constraint(None, 'foods', type_='foreignkey')
    op.create_foreign_key('foods_branch_id_fkey', 'foods', 'branches', ['branch_id'], ['id'])
    op.drop_column('foods', 'restaurant_id')
    op.drop_column('foods', 'owner_id')
    op.drop_column('foods', 'menu_type')
    op.drop_index(op.f('ix_branch_menus_id'), table_name='branch_menus')
    op.drop_table('branch_menus')
    # ### end Alembic commands ###
