"""add_receipt_and_status

Revision ID: d10882ccb6ba
Revises: a8238c39fcee
Create Date: 2026-04-07 21:30:35.891235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10882ccb6ba'
down_revision = 'a8238c39fcee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_foods_name'), 'foods', ['name'], unique=False)
    op.add_column('orders', sa.Column('receipt_url', sa.String(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('receipt_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'receipt_url')
    op.drop_column('user_subscriptions', 'status')
    op.drop_column('orders', 'receipt_url')
    op.drop_index(op.f('ix_foods_name'), table_name='foods')
    # ### end Alembic commands ###
